# Generated by Django 5.2.7 on 2025-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedstring',
            name='value',
            field=models.TextField(unique=True),
        ),
    ]
